/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.neu.csye6200.views;

import edu.neu.csye6200.DB;
import edu.neu.csye6200.controllers.Controller_Student;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author prudhvi
 */
public class AssignStudent extends javax.swing.JFrame {

    /**
     * Creates new form StudentAssigning
     */
    public AssignStudent() throws SQLException {
        initComponents();
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSID = new javax.swing.JTextField();
        lblSID = new javax.swing.JLabel();
        lblClass = new javax.swing.JLabel();
        txtClassID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAStudent = new javax.swing.JTable();
        btnAssign = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblTeacherName = new javax.swing.JLabel();
        txtTeacherName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        txtSID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSIDActionPerformed(evt);
            }
        });

        lblSID.setText("Student ID");

        lblClass.setText("Class ID");

        txtClassID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClassIDActionPerformed(evt);
            }
        });

        tblAStudent.setBackground(new java.awt.Color(204, 204, 255));
        tblAStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Student ID", "Student Name", "Class ID", "Teacher Name"
            }
        ));
        tblAStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAStudentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAStudent);

        btnAssign.setText("Assign");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblTeacherName.setText("Teacher Name");

        txtTeacherName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTeacherNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtClassID, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                    .addComponent(txtSID)
                    .addComponent(lblSID)
                    .addComponent(lblClass)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBack)
                            .addComponent(btnAssign)))
                    .addComponent(lblTeacherName)
                    .addComponent(txtTeacherName))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lblSID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblClass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtClassID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTeacherName)
                .addGap(4, 4, 4)
                .addComponent(txtTeacherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAssign)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBack)
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        // TODO add your handling code here:
         cId=Integer.parseInt(txtClassID.getText());
         sId=Integer.parseInt(txtSID.getText());
         
         Controller_Student contol_student = new Controller_Student();
        try {
            contol_student.modifyStudent(sId, cId);
            populateTable();
        } catch (SQLException ex) {
            Logger.getLogger(UpdateStudent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAssignActionPerformed

    private void txtClassIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClassIDActionPerformed
        // TODO add your handling code here:
        cId=Integer.parseInt(txtClassID.getText());
    }//GEN-LAST:event_txtClassIDActionPerformed

    private void txtSIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSIDActionPerformed
        // TODO add your handling code here:
        sId=Integer.parseInt(txtSID.getText());
    }//GEN-LAST:event_txtSIDActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.toBack();
        MainFrame frame = new MainFrame();
        frame.setVisible(true);
        frame.toFront();
        frame.setVisible(false);
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtTeacherNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTeacherNameActionPerformed
        // TODO add your handling code here:
        fname=txtTeacherName.getText();
        
    }//GEN-LAST:event_txtTeacherNameActionPerformed

    private void tblAStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAStudentMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tbl = (DefaultTableModel) tblAStudent.getModel();
         int srow = tblAStudent.getSelectedRow();
         
         txtSID.setText(tbl.getValueAt(srow,0).toString());
         txtClassID.setText(tbl.getValueAt(srow,2).toString());
         txtTeacherName.setText(tbl.getValueAt(srow,3).toString());
         
         
    }//GEN-LAST:event_tblAStudentMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AssignStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AssignStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AssignStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AssignStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AssignStudent().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(AssignStudent.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    public void populateTable() throws SQLException{
        DB database = DB.getObj();
        DefaultTableModel tbl = (DefaultTableModel) tblAStudent.getModel();
        tbl.setRowCount(0);
        ResultSet set = database.query("SELECT s.student_id,s.name,c.class_id,t.fname "
                    + " FROM student s,classroom c,teacher t WHERE s.class_id=c.class_id and "
                + "s.class_id=t.class_id "
                + "order by s.student_id ;");
        ResultSetMetaData rset = set.getMetaData();
        int j = rset.getColumnCount();
        while(set.next()){
            Vector vec = new Vector();
            for (int i=1;i<=j;i++){
                vec.add(set.getString("student_id"));
                vec.add(set.getString("name"));
                vec.add(set.getString("class_id"));
                vec.add(set.getString("fname"));
                  
            }
            tbl.addRow(vec);
        }
    }
    
    int sId;
    int cId;
    String fname;
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblClass;
    private javax.swing.JLabel lblSID;
    private javax.swing.JLabel lblTeacherName;
    private javax.swing.JTable tblAStudent;
    private javax.swing.JTextField txtClassID;
    private javax.swing.JTextField txtSID;
    private javax.swing.JTextField txtTeacherName;
    // End of variables declaration//GEN-END:variables
}
