/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.neu.csye6200.views;

import edu.neu.csye6200.controllers.Controller_Student;

/**
 *
 * @author prudhvi
 */
public class RegisterStudent extends javax.swing.JFrame {

    /**
     * Creates new form StudentRegister
     */
    public RegisterStudent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        heading = new javax.swing.JLabel();
        panelS = new javax.swing.JPanel();
        lblSName = new javax.swing.JLabel();
        lblSDob = new javax.swing.JLabel();
        txtSDob = new javax.swing.JTextField();
        txtSName = new javax.swing.JTextField();
        lblSParentID = new javax.swing.JLabel();
        txtSParentID = new javax.swing.JTextField();
        panelP = new javax.swing.JPanel();
        lblPName = new javax.swing.JLabel();
        lblPAddress = new javax.swing.JLabel();
        lblPPhone = new javax.swing.JLabel();
        txtPName = new javax.swing.JTextField();
        txtPAddress = new javax.swing.JTextField();
        txtPPhone = new javax.swing.JTextField();
        btnAddStudent = new javax.swing.JButton();
        btnRegBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        heading.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        heading.setText("Student Registration");

        panelS.setBackground(new java.awt.Color(204, 204, 255));
        panelS.setBorder(javax.swing.BorderFactory.createTitledBorder("Student Details"));

        lblSName.setText("Name");

        lblSDob.setText("Date of Birth");

        txtSDob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSDobActionPerformed(evt);
            }
        });

        txtSName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSNameActionPerformed(evt);
            }
        });

        lblSParentID.setText("Parent Id");

        javax.swing.GroupLayout panelSLayout = new javax.swing.GroupLayout(panelS);
        panelS.setLayout(panelSLayout);
        panelSLayout.setHorizontalGroup(
            panelSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSLayout.createSequentialGroup()
                        .addComponent(lblSName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                        .addComponent(txtSName, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSLayout.createSequentialGroup()
                        .addGroup(panelSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSDob)
                            .addComponent(lblSParentID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSDob, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(txtSParentID))))
                .addGap(157, 157, 157))
        );
        panelSLayout.setVerticalGroup(
            panelSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSName)
                    .addComponent(txtSName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(panelSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSDob)
                    .addComponent(txtSDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(panelSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSParentID)
                    .addComponent(txtSParentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        panelP.setBackground(new java.awt.Color(255, 204, 204));
        panelP.setBorder(javax.swing.BorderFactory.createTitledBorder("Parent Details"));

        lblPName.setText("Name");

        lblPAddress.setText("Address");

        lblPPhone.setText("Phone");

        txtPName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPNameActionPerformed(evt);
            }
        });

        txtPAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPAddressActionPerformed(evt);
            }
        });

        txtPPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPPhoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPLayout = new javax.swing.GroupLayout(panelP);
        panelP.setLayout(panelPLayout);
        panelPLayout.setHorizontalGroup(
            panelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPName)
                    .addComponent(lblPAddress)
                    .addComponent(lblPPhone))
                .addGap(42, 42, 42)
                .addGroup(panelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPName, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(txtPAddress)
                    .addComponent(txtPPhone))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        panelPLayout.setVerticalGroup(
            panelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(panelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPName)
                    .addComponent(txtPName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(panelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPAddress)
                    .addComponent(txtPAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(panelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPPhone)
                    .addComponent(txtPPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnAddStudent.setText("Add Student");
        btnAddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStudentActionPerformed(evt);
            }
        });

        btnRegBack.setText("Back");
        btnRegBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRegBack)
                        .addGap(116, 116, 116)
                        .addComponent(btnAddStudent))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(panelP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(heading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(heading)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddStudent)
                    .addComponent(btnRegBack))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStudentActionPerformed
        Controller_Student cs = new Controller_Student();
       pname = txtPName.getText();
       dob =txtSDob.getText();
       sname = txtSName.getText();
       paddress = txtPAddress.getText();
       pphone = txtPPhone.getText();
       
       cs.annexParentStudent(sname,  dob, pname, pphone, paddress);
       
       txtSName.setText("");
       txtPAddress.setText("");
       txtPPhone.setText("");
       txtPName.setText("");
       txtSDob.setText("");
    }//GEN-LAST:event_btnAddStudentActionPerformed

    private void btnRegBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegBackActionPerformed
       
        this.toBack();
        
        
        MainFrame frame = new MainFrame();
        frame.setVisible(true);
        frame.toFront();
        this.setVisible(false);
    }//GEN-LAST:event_btnRegBackActionPerformed

//     private void addParentBtnActionPerformed(java.awt.event.ActionEvent evt) {                                              
//        Controller_Student std = new Controller_Student();
//       pname = txtPName.getText();
//       dob =txtSDob.getText();
//       sname = txtSName.getText();
//       paddress = txtPAddress.getText();
//       pphone = txtPPhone.getText();
//       
//       std.addStudentAndParent(sname,  dob, pname, pphone, paddress);
//       
//       txtSName.setText("");
//       txtPAddress.setText("");
//       txtPPhone.setText("");
//       txtPName.setText("");
//    }   

    private void txtSDobActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_dobTextActionPerformed   
    dob =txtSDob.getText();
    System.out.println(dob);
        
    }// GEN-LAST:event_dobTextActionPerformed

    private void txtSNameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_nameTextActionPerformed
        
        sname = txtSName.getText();
    }// GEN-LAST:event_nameTextActionPerformed

    private void txtPAddressActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_addressTextActionPerformed
        paddress = txtPAddress.getText();
    }// GEN-LAST:event_addressTextActionPerformed

    private void txtPPhoneActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_phoneTextActionPerformed
        
        pphone = txtPPhone.getText();
    }// GEN-LAST:event_phoneTextActionPerformed

    private void txtPNameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_parentNameTextActionPerformed
        pname = txtPName.getText();
    }// GEN-LAST:event_parentNameTextActionPerformed

    /**
     * @param args the command line arguments
     */
    
    

    private String sname;
    private String dob;
    private String pname;
    private String pphone;
    private String paddress;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddStudent;
    private javax.swing.JButton btnRegBack;
    private javax.swing.JLabel heading;
    private javax.swing.JLabel lblPAddress;
    private javax.swing.JLabel lblPName;
    private javax.swing.JLabel lblPPhone;
    private javax.swing.JLabel lblSDob;
    private javax.swing.JLabel lblSName;
    private javax.swing.JLabel lblSParentID;
    private javax.swing.JPanel panelP;
    private javax.swing.JPanel panelS;
    private javax.swing.JTextField txtPAddress;
    private javax.swing.JTextField txtPName;
    private javax.swing.JTextField txtPPhone;
    private javax.swing.JTextField txtSDob;
    private javax.swing.JTextField txtSName;
    private javax.swing.JTextField txtSParentID;
    // End of variables declaration//GEN-END:variables
}
