/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.neu.csye6200.views;

import edu.neu.csye6200.controllers.TeacherController;
import edu.neu.csye6200.model.Teacher;

/**
 *
 * @author sowri
 */
public class UpdateDeleteTeacher extends javax.swing.JFrame {

    /**
     * Creates new form TeacherUpdateDelete
     */
    public UpdateDeleteTeacher() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        UpdateButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        ViewAllButton = new javax.swing.JButton();
        TeacherIDLabel = new javax.swing.JLabel();
        FirstNameLabel = new javax.swing.JLabel();
        LastNameLabel = new javax.swing.JLabel();
        AddressLabel = new javax.swing.JLabel();
        RatingLabel = new javax.swing.JLabel();
        PhoneNumberLabel = new javax.swing.JLabel();
        ClassIDLabel = new javax.swing.JLabel();
        TeacherIDTextBox = new javax.swing.JTextField();
        FirstNameTextBox = new javax.swing.JTextField();
        LastNameTextBox = new javax.swing.JTextField();
        RatingTextBox = new javax.swing.JTextField();
        PhoneNumberTextBox = new javax.swing.JTextField();
        ClassIDTextBox = new javax.swing.JTextField();
        AddressTextBox = new javax.swing.JTextField();
        BackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TEACHER UPDATE AND DELETE");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setPreferredSize(new java.awt.Dimension(165, 20));

        jPanel1.setBackground(new java.awt.Color(255, 153, 102));

        UpdateButton.setBackground(new java.awt.Color(255, 204, 204));
        UpdateButton.setText("UPDATE");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        DeleteButton.setBackground(new java.awt.Color(255, 102, 102));
        DeleteButton.setText("DELETE");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        ViewAllButton.setBackground(new java.awt.Color(204, 255, 204));
        ViewAllButton.setText("VIEW ALL");
        ViewAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewAllButtonActionPerformed(evt);
            }
        });

        TeacherIDLabel.setText("TEACHER ID");

        FirstNameLabel.setText("FIRST NAME");

        LastNameLabel.setText("LAST NAME");

        AddressLabel.setText("ADDRESS");

        RatingLabel.setText("RATING");

        PhoneNumberLabel.setText("PHONE NUMBER");

        ClassIDLabel.setText("CLASS ID");

        TeacherIDTextBox.setText("TeacherID");
        TeacherIDTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeacherIDTextBoxActionPerformed(evt);
            }
        });

        FirstNameTextBox.setText("firstName");
        FirstNameTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNameTextBoxActionPerformed(evt);
            }
        });

        LastNameTextBox.setText("lastName");
        LastNameTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNameTextBoxActionPerformed(evt);
            }
        });

        RatingTextBox.setText("rating");
        RatingTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RatingTextBoxActionPerformed(evt);
            }
        });

        PhoneNumberTextBox.setText("phoneNumber");
        PhoneNumberTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneNumberTextBoxActionPerformed(evt);
            }
        });

        ClassIDTextBox.setText("classID");
        ClassIDTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClassIDTextBoxActionPerformed(evt);
            }
        });

        AddressTextBox.setText("Address");
        AddressTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressTextBoxActionPerformed(evt);
            }
        });

        BackButton.setBackground(new java.awt.Color(204, 204, 255));
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ClassIDLabel)
                                .addGap(54, 54, 54)
                                .addComponent(ClassIDTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(RatingLabel)
                                .addGap(54, 54, 54)
                                .addComponent(RatingTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(PhoneNumberLabel)
                                .addGap(18, 18, 18)
                                .addComponent(PhoneNumberTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TeacherIDLabel)
                                    .addComponent(FirstNameLabel)
                                    .addComponent(LastNameLabel)
                                    .addComponent(AddressLabel))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(AddressTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(TeacherIDTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(134, 134, 134)
                                            .addComponent(ViewAllButton)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(FirstNameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(LastNameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(UpdateButton, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                            .addComponent(DeleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(BackButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                        .addGap(68, 68, 68))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {AddressTextBox, FirstNameTextBox, LastNameTextBox, TeacherIDTextBox});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ClassIDTextBox, PhoneNumberTextBox, RatingTextBox});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TeacherIDLabel)
                    .addComponent(TeacherIDTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ViewAllButton))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstNameLabel)
                    .addComponent(FirstNameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateButton))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LastNameLabel)
                    .addComponent(LastNameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteButton))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddressLabel)
                    .addComponent(AddressTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BackButton))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RatingLabel)
                    .addComponent(RatingTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhoneNumberLabel)
                    .addComponent(PhoneNumberTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClassIDLabel)
                    .addComponent(ClassIDTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        Teacher TEACHER = new Teacher();
         try{
            Integer EmployeeId=Integer.parseInt(TeacherIDTextBox.getText());
            TEACHER.setEmployee_Id(EmployeeId);
        }
        catch(Exception e){
            TEACHER.setEmployee_Id(0);
        }
        
        TeacherController teachercontroller = new TeacherController();
        System.out.println(TEACHER.toString());
        teachercontroller.delete(TEACHER);
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void ViewAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewAllButtonActionPerformed
        //view all
                TeacherController teachercontroller = new TeacherController();
        teachercontroller.viewTeachers();
    }//GEN-LAST:event_ViewAllButtonActionPerformed

    private void TeacherIDTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeacherIDTextBoxActionPerformed
        //teacher id
    }//GEN-LAST:event_TeacherIDTextBoxActionPerformed

    private void FirstNameTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNameTextBoxActionPerformed
        //firstname
    }//GEN-LAST:event_FirstNameTextBoxActionPerformed

    private void LastNameTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNameTextBoxActionPerformed
        //lastname
    }//GEN-LAST:event_LastNameTextBoxActionPerformed

    private void RatingTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RatingTextBoxActionPerformed
        //rating
    }//GEN-LAST:event_RatingTextBoxActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        //update button
        Teacher TEACHER = new Teacher();
        if (!FirstNameTextBox.getText().equals("First Name")) {
            TEACHER.setFirst_Name(FirstNameTextBox.getText());
        } else {
            TEACHER.setFirst_Name("");
        }
        if (!LastNameTextBox.getText().equals("Last Name")) {
            TEACHER.setLast_Name(LastNameTextBox.getText());
        } else {
            TEACHER.setLast_Name("");
        }
        if (!PhoneNumberTextBox.getText().equals("Phone Number")) {
            TEACHER.setPhnNo(PhoneNumberTextBox.getText());
        } else {
            TEACHER.setPhnNo("");
        }
        
//        try {
            Double rating = Double.parseDouble(RatingTextBox.getText());
            TEACHER.setRating(rating);
//        } catch (Exception e) {
//            TEACHER.setRating(0.0);
//        }
        try {
            Integer EmployeeId = Integer.parseInt(TeacherIDTextBox.getText());
            TEACHER.setEmployee_Id(EmployeeId);
        } catch (Exception e) {
            TEACHER.setEmployee_Id(0);
        }
        if (!AddressTextBox.getText().equals("Address")) {
            TEACHER.setAddres(AddressTextBox.getText());
        } else {
            TEACHER.setAddres("");
        }
        TeacherController teachercontroller = new TeacherController();
        System.out.println(TEACHER.toString());
        teachercontroller.update(TEACHER);


    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void PhoneNumberTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneNumberTextBoxActionPerformed
        // phone number
    }//GEN-LAST:event_PhoneNumberTextBoxActionPerformed

    private void ClassIDTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClassIDTextBoxActionPerformed
        // class id
    }//GEN-LAST:event_ClassIDTextBoxActionPerformed

    private void AddressTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressTextBoxActionPerformed
        // address
    }//GEN-LAST:event_AddressTextBoxActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        this.toBack();
        MainFrame MF = new MainFrame();
        MF.setVisible(true);
        MF.toFront();
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateDeleteTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateDeleteTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateDeleteTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateDeleteTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateDeleteTeacher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressLabel;
    private javax.swing.JTextField AddressTextBox;
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel ClassIDLabel;
    private javax.swing.JTextField ClassIDTextBox;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JLabel FirstNameLabel;
    private javax.swing.JTextField FirstNameTextBox;
    private javax.swing.JLabel LastNameLabel;
    private javax.swing.JTextField LastNameTextBox;
    private javax.swing.JLabel PhoneNumberLabel;
    private javax.swing.JTextField PhoneNumberTextBox;
    private javax.swing.JLabel RatingLabel;
    private javax.swing.JTextField RatingTextBox;
    private javax.swing.JLabel TeacherIDLabel;
    private javax.swing.JTextField TeacherIDTextBox;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JButton ViewAllButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
